### ISSUE TITLE
automatic selection

### ISSUE THREAD

**Issue by Vedsted** [sweat-tek/SB5-MAI-E18-2#9]
**Subtask**
- [ ] Select all: As a user I want to be able to select all figures, so that I don't have to select every figure manually
- [ ] Deselect all: As a user I want to be able to deselect all figures, so that I don't have to deselect every figure manually
- [ ] Select same: As a user I want to be able to select figures of same type, so that I don't have to select every type individually
